"""Add risk_assessments table and repository asset context fields

Revision ID: 2026_08_22_1200
Revises: 2026_08_22_0000
Create Date: 2026-08-22 12:00:00.000000

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2026_08_22_1200'
down_revision: Union[str, None] = '2026_08_22_0000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('asset_type', sa.String(length=50), nullable=False, server_default='SOURCE_CODE'))
    op.add_column('repositories', sa.Column('asset_criticality', sa.String(length=50), nullable=False, server_default='UNKNOWN'))
    op.add_column('repositories', sa.Column('exposure', sa.String(length=50), nullable=False, server_default='UNKNOWN'))

    op.create_table(
        'risk_assessments',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('finding_id', sa.UUID(), nullable=False),
        sa.Column('risk_score', sa.Integer(), nullable=False),
        sa.Column('risk_level', sa.String(length=50), nullable=False),
        sa.Column('priority', sa.String(length=50), nullable=False),
        sa.Column('severity_factor', sa.Float(), nullable=False, server_default='5.0'),
        sa.Column('exploitability_factor', sa.Float(), nullable=False, server_default='0.4'),
        sa.Column('exposure_factor', sa.Float(), nullable=False, server_default='0.4'),
        sa.Column('asset_criticality_factor', sa.Float(), nullable=False, server_default='0.4'),
        sa.Column('confidence_factor', sa.Float(), nullable=False, server_default='1.0'),
        sa.Column('explanation', sa.Text(), nullable=True),
        sa.Column('recommended_action', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('finding_id')
    )
    op.create_index(op.f('ix_risk_assessments_id'), 'risk_assessments', ['id'], unique=False)
    op.create_index(op.f('ix_risk_assessments_finding_id'), 'risk_assessments', ['finding_id'], unique=True)
    op.create_index(op.f('ix_risk_assessments_risk_score'), 'risk_assessments', ['risk_score'], unique=False)
    op.create_index(op.f('ix_risk_assessments_risk_level'), 'risk_assessments', ['risk_level'], unique=False)
    op.create_index(op.f('ix_risk_assessments_priority'), 'risk_assessments', ['priority'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_assessments_priority'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_risk_level'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_risk_score'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_finding_id'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_id'), table_name='risk_assessments')
    op.drop_table('risk_assessments')

    op.drop_column('repositories', 'exposure')
    op.drop_column('repositories', 'asset_criticality')
    op.drop_column('repositories', 'asset_type')
    # ### end Alembic commands ###
